version: '3'
services:
  backendserver:
    container_name: backend
    build: ./backendserver
    ports:
      - "8000:8000"
    volumes:
      - ./backendserver/models:/models

  frontendserver:
    container_name: frontend
    build: ./frontend
    ports:
      - "4173:4173"
    

  postgres:
    image: postgres:13
    container_name: job_database
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./job_db/pg:/var/lib/postgresql
      - ./job_db/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      